stages:
  - stage: Build
    displayName: 'Build Stage'
    jobs:
      - job: Build
        displayName: 'Build the Python Function App'
        pool:
          name: 'default'
        steps:
          # Python is pre-installed on the self-hosted agent
          - script: |
              py -m pip install --upgrade pip
              pip install -r requirements.txt
            displayName: 'Install dependencies'

  - stage: Test
    displayName: 'Test Stage'
    jobs:
      - job: Test
        displayName: 'Run Unit Tests'
        pool:
          name: 'default'
        steps:
          - script: |
              pip install pytest
              pytest
            displayName: 'Run Pytest'

  - stage: Deploy
    displayName: 'Deploy to Azure'
    jobs:
      - job: Deploy
        displayName: 'Deploy Python Function to Azure'
        pool:
          name: 'default'
        steps:
          - task: AzureFunctionApp@1
            inputs:
              azureSubscription: 'azuredev'  # Azure service connection name
              appName: 'ict4nmnm'              # Actual Azure Function App name
              package: '$(System.DefaultWorkingDirectory)'
