stages:
  - stage: Build
    displayName: 'Build Stage'
    jobs:
      - job: Build
        displayName: 'Build the Function App'
        pool:
          name: 'default'
        steps:
          - task: UseDotNet@2
            inputs:
              packageType: 'sdk'
              version: '5.x'
              installationPath: $(Agent.ToolsDirectory)/dotnet
          - script: |
              dotnet restore FunctionApp/FunctionApp.csproj
              dotnet build FunctionApp/FunctionApp.csproj --configuration Release
            displayName: 'Build the Azure Function'

  - stage: Test
    displayName: 'Test Stage'
    jobs:
      - job: Test
        displayName: 'Run Unit Tests'
        pool:
          name: 'default'  # Use the default pool or specify a custom one
        steps:
          - script: |
              dotnet test FunctionApp.Tests/FunctionApp.Tests.csproj --configuration Release
            displayName: 'Run Tests'

  - stage: Deploy
    displayName: 'Deploy to Azure'
    jobs:
      - job: Deploy
        displayName: 'Deploy Function to Azure'
        pool:
          name: 'default'
        steps:
          - task: AzureFunctionApp@1
            inputs:
              azureSubscription: 'azuredev'  # Azure service connection name
              appName: 'ict4nm'            # Actual Azure Function App name
              package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
