trigger:
  - main

pool:
  vmImage: 'windows-latest'

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.12'
          - script: |
              python --version
              pip install --upgrade pip
              pip install -r requirements.txt
            displayName: 'Install and setup Python dependencies'
          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/function.zip'
              replaceExistingArchive: true
          - publish: '$(Build.ArtifactStagingDirectory)/function.zip'
            artifact: drop

  - stage: Test
    dependsOn: Build
    jobs:
      - job: Test
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.12'
          - script: |
              pip install pytest
              pytest
            displayName: 'Run Pytest'

  - stage: Deploy
    dependsOn: Build
    jobs:
      - job: Deploy
        steps:
          - download: current
            artifact: drop
          - task: AzureFunctionApp@1
            inputs:
              azureSubscription: 'azuredev'
              appName: 'ict4nmnm'
              package: '$(Pipeline.Workspace)/drop/function.zip'
